server: 
  port: 9527
 
spring: 
  profiles: dev
  application:
    name: udm-zuul-app
 
eureka: 
  client: 
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka  
  instance:
    instance-id: udm-zuul-ins
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: microservicecloud-dept
  prefix: /www
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
    user-consumer.serviceId: udm-user-consumer-app
    user-consumer.path: /uc/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

