server: 
  port: 9527
 
spring: 
  profiles: dev
  application:
    name: udm-zuul
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka  
  instance:
    instance-id: udm.zuul.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: microservicecloud-dept
  prefix: /www
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

